[workspace]
members = ["packages/*"]
default-members = ["packages/gateau"]
resolver = "2"

[profile.release-opt]
inherits = "release"
strip = true
panic = "abort"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[profile.release-debuginfo]
inherits = "release"
debug = true
