[package]
name = "gateau"
version = "0.2.0"
edition = "2021"

[dependencies]
cfg-if = "1.0.0"
cookie = "0.17.0"
http = "0.2.8"
once_cell = "1.17.0"
rusqlite = { version = "0.29.0", features = ["functions"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
tini = "1.3.0"
dirs-next = "2.0.0"
regex = "1.8.1"
thiserror = "1.0.40"

[features]
default = []
bundled = ["rusqlite/bundled"]

[target.'cfg(unix)'.dependencies]
aes = "0.8.2"
cbc = { version = "0.1.2", features = ["std"] }
pbkdf2 = { version = "0.12.1", features = ["sha1", "std", "simple"] }

[target.'cfg(any(target_os = "macos", target_os = "linux"))'.dependencies]
keyring = "1.2.0"

[target.'cfg(windows)'.dependencies]
aes-gcm = "0.10.1"
base64ct = { version = "1.5.3", features = ["std"] }
windows = { version = "0.48.0", features = [
    "Win32_Security_Cryptography",
    "Win32_System_Memory",
    "Win32_Foundation",
] }
