name: Generate project changelog

on:
  push:
    branches:
      - main
  

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate the release changelog
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with:
          config: cliff/complete.toml
          args: -vvv --latest
        env:
          OUTPUT: CHANGELOG.md

      - name: Update changelog
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs(changelog): update changelog"
          token: ${{ secrets.GIT_CLIFF_PAT }}