name: Generate changelog and create release

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  tag:
    name: Generate changelog and create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate the release changelog
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with:
          config: cliff/release.toml
          args: -vvv --latest

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.git-cliff.outputs.content }}

  release:
    name: Build binaries and upload to release
    needs: tag
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl

          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            target: x86_64-pc-windows-gnu

          - os: macos-latest
            target: x86_64-apple-darwin

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install musl-tools
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: sudo apt-get install musl-tools

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Create archive
        id: archive
        shell: bash
        run: |
          ARCHIVE_PATH=$(cargo xtask dist --profile=release-opt --target=${{ matrix.target }} \
                        --features=bundled README.md LICENSE)
          [[ $? == 0 ]] || exit 1
          # https://github.com/softprops/action-gh-release/issues/79
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            ARCHIVE_PATH=${ARCHIVE_PATH//\\/\/}
          fi
          echo "path=$ARCHIVE_PATH" >> $GITHUB_OUTPUT


      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.archive.outputs.path }}
